### ISSUE TITLE
Remove Librpitx

### ISSUE THREAD

**Issue by DarkBlueProjects** [YoungDydlak/web-rpi-fm#2]
Hello I was wondering if i could change what The words on the radio were.

I want it to look like this

[songname]
[artist]

Instead of
Librpitx
[whats playing]

**Comment by YoungDydlak** [comment]
Yeah, go ahead.

**Comment by dawiddyd** [comment]
Pifmrds station name limit is only 8 characters so I replaced song name with song artist (Usually artist name is shorter than song name). Unfortunately, song artist name is cropped to 8 characters long.
